version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112661735.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`        
      - docker build -t flask-app .
      - docker tag flask-app:latest 471112661735.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`.
      - docker push 471112661735.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
      - printf '[{"name":"flask-app","imageUri":"%s"}]' 471112661735.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest  > imagedefinitions.json

artifacts:
    files: imagedefinitions.json